#!/usr/bin/env bash
# =============================================================================
# gen-acl.sh — Generate Squid ACL files from agent allowlists
#
# Usage: gen-acl.sh <slot> <agent-type> <allowlist-file>
#
# Creates:
#   /etc/squid/acls/vm{slot}-domains.txt   — domain list for this VM
#   /etc/squid/acls/vm-{slot}.conf         — Squid ACL rules for this VM
#
# Also regenerates /etc/squid/acls/all-allowed-domains.txt (union of all VMs)
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SANDBOX_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

source "${SANDBOX_ROOT}/lib/common.sh"
ensure_global_compiled

SLOT="${1:?Usage: gen-acl.sh <slot> <agent-type> <allowlist-file>}"
AGENT_TYPE="${2:?Usage: gen-acl.sh <slot> <agent-type> <allowlist-file>}"
ALLOWLIST_FILE="${3:?Usage: gen-acl.sh <slot> <agent-type> <allowlist-file>}"

ACL_DIR="/etc/squid/acls"
mkdir -p "${ACL_DIR}"

# Squid rejects overlapping entries in ssl::server_name / dstdomain ACLs
# (6.x: FATAL "is a subdomain of"; 7.x: tolerated but mis-matched -> allowlisted
# HTTPS domains get bumped). Drop any entry already covered by a broader
# leading-dot entry, e.g. drop "production.cloudflare.docker.com" when
# ".docker.com" is present, and "scholar.google.com" when ".google.com" is.
dedupe_domains() {
    # Reads domain entries on stdin, prints the overlap-free set. Uses `-c` so
    # stdin stays the piped domains (a `-` + heredoc would consume stdin as the
    # script and read zero domains).
    python3 -c '
import sys
ents=[]
for l in sys.stdin:
    l=l.strip()
    if l and not l.startswith("#") and l not in ents:
        ents.append(l)
def covered(e):
    for p in ents:
        if p == e or not p.startswith("."):
            continue
        if e == p[1:] or e.endswith(p):   # "google.com" or "*.google.com" vs ".google.com"
            return True
    return False
for e in ents:
    if not covered(e):
        print(e)
'
}

SUBNET="${VM_SUBNET_PREFIX:-10.0}.${SLOT}.0/24"
DOMAINS_FILE="${ACL_DIR}/vm${SLOT}-domains.txt"
CONF_FILE="${ACL_DIR}/vm-${SLOT}.conf"

# --- Extract LiteLLM host from config (always allowed) ---
LLM_HOST=""
if [[ -n "${LLM_API_BASE:-}" ]]; then
    LLM_HOST=$(echo "${LLM_API_BASE}" | sed -E 's|https?://||; s|:[0-9]+.*||; s|/.*||')
fi

# --- Generate domain list (deduped/overlap-free) ---
{
    echo "# Allowed domains for VM slot ${SLOT} (${AGENT_TYPE})"
    echo "# Generated: $(date -Iseconds)"
    {
        # `grep -v` exits non-zero when it filters out every line (e.g. an agent
        # with an empty/comment-only allowlist whose egress is just the LLM
        # passthrough). Under `set -euo pipefail` that would abort the pipe
        # subshell BEFORE the LLM host below is emitted — and fail the launch —
        # so tolerate "no matches" explicitly.
        if [[ -f "${ALLOWLIST_FILE}" ]]; then
            grep -v '^\s*#' "${ALLOWLIST_FILE}" | grep -v '^\s*$' || true
        fi
        [[ -n "${LLM_HOST}" ]] && echo "${LLM_HOST}" || true
    } | dedupe_domains
} > "${DOMAINS_FILE}"

# --- Generate Squid ACL config for this VM ---
# Per-VM HTTPS filtering is done in ssl_bump (step2, after the SNI is peeked) —
# NOT in http_access, which runs before the peek and would match the dest IP,
# deny, and trigger a client-first bump. This file is included inside the
# ssl_bump block in squid-base.conf, between `peek step1` and `terminate all`.
cat > "${CONF_FILE}" <<EOF
# VM Slot ${SLOT}: ${AGENT_TYPE}
# Source subnet: ${SUBNET}
acl vm${SLOT}_src src ${SUBNET}
acl vm${SLOT}_domains ssl::server_name "${DOMAINS_FILE}"
ssl_bump splice vm${SLOT}_src vm${SLOT}_domains
EOF

# --- Regenerate combined include file (all per-VM confs) ---
INCLUDE_FILE="${ACL_DIR}/vm-acls.conf"
echo "# Per-VM ACLs — auto-generated by gen-acl.sh" > "${INCLUDE_FILE}"
echo "# Generated: $(date -Iseconds)" >> "${INCLUDE_FILE}"
for f in "${ACL_DIR}"/vm-[0-9]*.conf; do
    [[ -f "$f" ]] && cat "$f" >> "${INCLUDE_FILE}"
done

# --- Regenerate combined allowed domains list (deduped/overlap-free) ---
{
    echo "# Combined allowed domains (all VMs)"
    echo "# Generated: $(date -Iseconds)"
    # `|| true` so an all-empty union (every agent on LLM-passthrough only) does
    # not abort under pipefail/set -e.
    { cat "${ACL_DIR}"/vm*-domains.txt 2>/dev/null | grep -v '^\s*#' | grep -v '^\s*$' | sort -u || true; } \
        | dedupe_domains
} > "${ACL_DIR}/all-allowed-domains.txt"

echo "ACL generated for VM slot ${SLOT} (${AGENT_TYPE}): ${CONF_FILE}"
